clear; clc; close all;

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/jonno/Downloads/pico/blink_any/imu.csv
%
% Auto-generated by MATLAB on 20-Sep-2025 15:51:46

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timestamp_us", "accel_x", "accel_y", "accel_z", "mag_x", "mag_y", "mag_z", "gyro_x", "gyro_y", "gyro_z"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
imu = readtable("/Users/jonno/Downloads/pico/blink_any/imu.csv", opts);


%% Clear temporary variables
clear opts

time_offset = imu.timestamp_us(1);

imu.time_s = (imu.timestamp_us - time_offset) / 1000000;


time_to_find = 5; % seconds
[~, time_position] = min(abs(imu.time_s - time_to_find));

gyro_bias_x = mean(imu.gyro_x(1:time_position));
gyro_bias_y = mean(imu.gyro_y(1:time_position));
gyro_bias_z = mean(imu.gyro_z(1:time_position));

imu.gyro_x_no_bias = (imu.gyro_x - gyro_bias_x) * 0.00875;
imu.gyro_y_no_bias = (imu.gyro_y - gyro_bias_y) * 0.00875;
imu.gyro_z_no_bias = (imu.gyro_z - gyro_bias_z) * 0.00875;

imu.angle_x = (cumsum(imu.gyro_x_no_bias));
imu.angle_y = (cumsum(imu.gyro_y_no_bias));
imu.angle_z = (cumsum(imu.gyro_z_no_bias));

