%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/jonno/MATLAB-Drive/masters-rocket-control-repository/MATLAB_Toolbox/Phoenix_EKF/phoenix_sensor_sim_output.csv
%
% Auto-generated by MATLAB on 29-Oct-2025 11:32:23

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time_s", "Accel_X_m_s2", "Accel_Y_m_s2", "Accel_Z_m_s2", "New_Accel_Data_Flag", "Gyro_X_rad_s", "Gyro_Y_rad_s", "Gyro_Z_rad_s", "New_Gyro_Data_Flag", "Mag_X_uT", "Mag_Y_uT", "Mag_Z_uT", "New_Mag_Data_Flag", "Ref_Pos_X_m", "Ref_Pos_Y_m", "Ref_Pos_Z_m", "Ref_Vel_X_m_s", "Ref_Vel_Y_m_s", "Ref_Vel_Z_m_s", "Ref_Att_Roll_deg", "Ref_Att_Pitch_deg", "Ref_Att_Yaw_deg"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
phoenix_sensor_sim_output = readtable("/Users/jonno/MATLAB-Drive/masters-rocket-control-repository/MATLAB_Toolbox/Phoenix_EKF/phoenix_sensor_sim_output.csv", opts);


%% Clear temporary variables
clear opts