% Load the data using readtable
% ...existing code...

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/jonno/MATLAB-Drive/Rocket-Model-Simulation/STEVE_Simulator/STeVe-Contour.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 04-Mar-2025 16:26:32

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:C50";

% Specify column names and types
opts.VariableNames = ["X", "Y", "Var3"];
opts.VariableTypes = ["double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");

% Import the data
STeVe_Contour = readtable("/Users/jonno/MATLAB-Drive/Rocket-Model-Simulation/STEVE_Simulator/STeVe_Data/STeVe-Contour.xlsx", opts, "UseExcel", false);

%% Clear temporary variables
clear opts

% Extract coordinates
X = STeVe_Contour.X;
Y = STeVe_Contour.Y;

% Create full symmetric profile
X_full = [X; flipud(X(2:end))];  % Avoid duplicating the tip point
Y_full = [Y; -flipud(Y(2:end))];

% Plot with annotations
figure;
plot(X_full, Y_full, 'b-', 'LineWidth', 1.5);
hold on;

% Highlight key features
plot(X(1), Y(1), 'ro', 'MarkerSize', 8, 'DisplayName', 'Tip');                 % Tip
plot(X(6), Y(6), 'g^', 'MarkerSize', 8, 'DisplayName', 'VK Start');           % Von Karman start
plot(X(end-1), Y(end-1), 'mv', 'MarkerSize', 8, 'DisplayName', 'VK End');     % Von Karman end
plot(X(end), Y(end), 'ks', 'MarkerSize', 8, 'DisplayName', 'Straight End');   % Cylinder end

% Formatting
axis equal;
grid on;
xlabel('Axial Position (m)');
ylabel('Radial Position (m)');
title('STeVe Rocket Contour Profile');
legend('Location', 'best');
hold off;
